#!/bin/zsh -f

# Called after a command has failed with an optional error message. We've
# captured the standard error of the failed command, so an error message is
# probably not necessary.

# Note that the throw comes from invalid syntax. In the inspiration thread TK
# suggests using ${:?} because it is valid syntax and invalid syntax may some
# day become valid, so this is resistent to that change. However, ${:?} will
# exit on the line where it is invoked whereas the bad syntax will propagate the
# error to a finally block.

# Inspiration. There are other try/catch Zsh hacks out there.
# https://www.zsh.org/mla/users/2005/msg00162.html

# Similiary `set -e`, which is Zsh is `setopt localoptions errexit` will exit
# immediately and `setopt localoptions errreturn` will trigger the `always`,
# but it means having to deal with `set -e` everywhere in the program.

# Thoughts on `set -e`.
# https://www.mail-archive.com/bug-bash@gnu.org/msg19497.html

# Remember that we're not trying to make a try/catch, though. We're trying to
# make a block formatter according to requirements above.
o_block[code]=$?

if [[ $1 = -c ]]; then
    o_block[code]=${2:-$o_block[code]}
    shift
    (( $# )) && shift
fi

typeset message
if (( $# )); then
    printf -v message "$@"
    o_block[abend]=$message
fi

# We need to affect a throw, so we need to do something naughty, but not
# something that will exit the program, like calling `exit`. This comes straight
# from the /usr/share/zsh/functions/Exceptions/throw function.
typeset -r THROW
THROW= 2>/dev/null
